import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Generates a PDF for a generic tabular report
 * @param {string} title - Report title
 * @param {Array} columns - Array of column headers
 * @param {Array} data - Array of row objects (col1, col2, etc.)
 * @param {string} dateRange - Optional date range string for the header
 */
export const generateReportPDF = (title, columns, data, dateRange = '') => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    
    // Add Logo or Header Title
    doc.setFontSize(18);
    doc.setTextColor(38, 166, 154); // Teal
    doc.text(title, 14, 22);
    
    // Add Date Info
    doc.setFontSize(10);
    doc.setTextColor(100);
    const dateStr = dateRange || `Generated on: ${new Date().toLocaleString()}`;
    doc.text(dateStr, 14, 30);
    
    // Add horizontal line
    doc.setDrawColor(243, 196, 101); // Yellow accent
    doc.setLineWidth(1);
    doc.line(14, 35, 60, 35);

    // Prepare table data
    const tableRows = data.map(row => Object.values(row));

    autoTable(doc, {
        startY: 45,
        head: [columns],
        body: tableRows,
        theme: 'grid',
        headStyles: {
            fillColor: [31, 41, 55], // Gray-900
            textColor: [255, 255, 255],
            fontSize: 10,
            fontStyle: 'bold'
        },
        styles: {
            fontSize: 9,
            cellPadding: 3
        },
        alternateRowStyles: {
            fillColor: [249, 250, 251] // Gray-50
        },
        margin: { left: 14, right: 14 }
    });

    // Add Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
            `Page ${i} of ${pageCount} - Generated by YMS Admin`,
            pageWidth / 2,
            doc.internal.pageSize.height - 10,
            { align: 'center' }
        );
    }

    doc.save(`${title.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`);
};
